openapi: 3.0.0
info:
  title: Bitize
  version: '1.0'
  contact:
    name: Carlos Tirabassi
    email: carlos@bitize.com.br
  description: API de integração com o backend do Bitize
servers:
  - url: 'https://api.bitize.com.br'
    description: Produção
  - url: 'https://api-tst.bitize.com.br'
    description: Testes
paths:
  /auth:
    get:
      summary: Autenticação - Refresh Token
      tags:
        - refresh token
        - login
        - auth
        - autenticação
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: Token de acesso
                  refresh_token:
                    type: string
                    description: Refresh token
                  expiration_access_token:
                    type: string
                    description: Data de expiração do token de acesso
                  expiration_refresh_token:
                    type: string
                    description: Data de expiração do refresh token
              examples:
                Exemplo de retorno:
                  value:
                    access_token: eyJhbGcFOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyApZCI6IjI1NGJjMGU4LWU5NTMtNDRkZS05ZTUELTI0YWNiYTM1MDAyZiIsImlhdCI6MTYBMTk1MjI1OSwiZXhwIjoxNjEyMDM4NjU5fQ.hQL7SANKEVjepTgoPaBk6h0vZLOdu4tnVC6BIa3gQO0
                    refresh_token: eyJhbGcAOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJAZCI6IjI1NGJjMGU4LWU5NTMtNDRkZS05ZTUDLTa0YWNiYTM1MDAyZiIsImlhdCI6MXYxMTk1MjI1OSwiZXhwIjoxNjEyMTI1MDU5fQ.KdCuLqxBFxNaXwHgfjmyWd8X6BTAcpbCoCuRcnRGBxg
                    expiration_access_token: '2021-01-30T20:30:59.058Z'
                    expiration_refresh_token: '2021-01-31T20:30:59.058Z'
      operationId: get-signin
      description: Endpoint para obtenção de um novo token através de um refresh token válido
      parameters:
        - schema:
            type: string
          in: query
          name: refresh_token
          description: Refresh token
          required: true
      security: []
    post:
      summary: Autenticação - Token de Acesso
      operationId: post-signin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: Token de acesso
                  refresh_token:
                    type: string
                    description: Refresh token
                  expiration_access_token:
                    type: string
                    description: Data de expiração do token de acesso
                  expiration_refresh_token:
                    type: string
                    description: Data de expiração do refresh token
              examples:
                Exemplo de retorno:
                  value:
                    access_token: eyJhbGcFOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyApZCI6IjI1NGJjMGU4LWU5NTMtNDRkZS05ZTUELTI0YWNiYTM1MDAyZiIsImlhdCI6MTYBMTk1MjI1OSwiZXhwIjoxNjEyMDM4NjU5fQ.hQL7SANKEVjepTgoPaBk6h0vZLOdu4tnVC6BIa3gQO0
                    refresh_token: eyJhbGcAOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJAZCI6IjI1NGJjMGU4LWU5NTMtNDRkZS05ZTUDLTa0YWNiYTM1MDAyZiIsImlhdCI6MXYxMTk1MjI1OSwiZXhwIjoxNjEyMTI1MDU5fQ.KdCuLqxBFxNaXwHgfjmyWd8X6BTAcpbCoCuRcnRGBxg
                    expiration_access_token: '2021-01-30T20:30:59.058Z'
                    expiration_refresh_token: '2021-01-31T20:30:59.058Z'
      description: Endpoint para obtenção do token de acesso a API
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                consumer_key:
                  type: string
                  description: Chave de consumo do API
                secret_key:
                  type: string
                  description: Chave secreta de acesso a API
              required:
                - consumer_key
                - secret_key
            examples:
              example-1:
                value:
                  consumer_key: string
                  secret_key: string
      tags:
        - auth
        - login
        - autenticação
        - token
      parameters:
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          required: true
      security: []
    parameters: []
components:
  schemas: {}
  securitySchemes:
    Token:
      type: http
      scheme: bearer
tags:
  - name: auth
  - name: login
  - name: autenticação
  - name: token
  - name: refresh token
security:
  - Token: []
